

@startuml  UseCase
left to right direction
actor Player
rectangle QuoridorGame {


Player -left- (Sign In)
Player -- (StartGame)
Player -- (Manage List Of Friends)
Player -- (Chat With Friends)
Player -- (Check ELO Ranking)

(StartGame) <|-- (ResumeGame)
(StartGame) <|-- (JoinGame)
(StartGame) <|-- (NewGame)

(Invite Friends) .-up-> (NewGame) : extends
(Configure) .-up-> (NewGame) : include

(Play) .--> (StartGame) : include
(GiveUp) .--> (StartGame) : extends
(Pause/Save Game) .--> (StartGame) : exntends
(Play) <|-up- (Move)
(Play) <|-up- (PlaceWall)

(Valide User) .-up-> (Sign In) : include
(Sign Up) .-up-> (Sign In) : extends


}
@enduml
